### ISSUE TITLE
load_csv for a single-column csv drops the first row if nil (nit)

### ISSUE THREAD

**Issue by kylewhite21** [elixir-nx/explorer#588] opened 2023-05-01 17:36 UTC
When loading a single-column csv into a DataFrame, if the first column is nil and represented by only a `\n` then it is dropped in the DataFrame.

```
# 2x1 csv with data [nil, 3]
Explorer.DataFrame.load_csv!("x\n\n3\n")

# results are 1x1
# #Explorer.DataFrame<
#   Polars[1 x 1]
#   x integer [3]
# >
```

Just commenting that Pandas will write empty quotes and Explorer of course doesn't
```
>>> pd.DataFrame({"x": [pd.NA, 3]}).to_csv(index=False)
'x\n""\n3\n'
```

```
iex> Explorer.DataFrame.new(%{x: [nil, 3]}) |> Explorer.DataFrame.dump_csv!
"x\n\n3\n"
```

**Comment by philss** [comment] 2023-05-25 18:57
I think the latest update of Polars - 0.29 - fixed the issue.
I couldn't reproduce with the version from the `main` branch.
So I'm closing the issue now, and I'm going to add a note to the CHANGELOG.md.

Thanks for reporting this, @kylewhite21!

**Closed by philss** 2023-05-25 18:57 UTC
