### ISSUE TITLE
Corrupting data when converting integers after DataFrame.to_map()

### ISSUE THREAD

**Issue by kimjoaoun** [elixir-nx/explorer#96] opened 2022-01-09 16:42 UTC
While I was using some functions I saw a weird behaviour when converting a DataFrame to a map.
In the `fossil_fuels` dataset, the `bunker_fuels` column value that originally was the integer `9` became a `'\t'`.

```
iex(1)> df = Explorer.Datasets.fossil_fuels()
iex(2)> df  |> Explorer.DataFrame.slice(0, 1) |> Explorer.DataFrame.to_map()
%{          
  bunker_fuels: '\t',
  cement: [5],
  country: ["AFGHANISTAN"],
  gas_flaring: [0],
  gas_fuel: 'J',
  liquid_fuel: [1601],
  per_capita: [0.08],
  solid_fuel: [627],
  total: [2308],
  year: [2010]
}
```

And it gets worse, because it is not just a printing problem, if I try to parse the map to a list using Map.to_list(), IEx returns a list with the same '\t' character

```
iex(3)> df  |> Explorer.DataFrame.slice(0, 1) |> Explorer.DataFrame.to_map() |> Map.to_list()
[
  bunker_fuels: '\t',
  cement: [5],
  country: ["AFGHANISTAN"],
  gas_flaring: [0],
  gas_fuel: 'J',
  liquid_fuel: [1601],
  per_capita: [0.08],
  solid_fuel: [627],
  total: [2308],
  year: [2010]
]
```

**Comment by cigrainger** [comment] 2022-01-10 00:04
`gas_fuel` appears to also be corrupted, returning `'J'`. Looking into this with urgency.

**Comment by philss** [comment] 2022-01-10 00:40
@kimjoaoun @cigrainger hey guys, I think this is just a matter of how Elixir is printing the lists. If you try this:

```elixir
df = Explorer.Datasets.fossil_fuels()
df  |> Explorer.DataFrame.slice(0, 1) |> Explorer.DataFrame.to_map() |> IO.inspect(charlists: :as_lists)
```

You can see that the inspected value is returned correctly. This is because by default IEx will try to infer the type of a list. Sometimes it is detected as `charlist`. See https://hexdocs.pm/elixir/Inspect.Opts.html for details.

To disable this behavior in IEx, you can run `IEx.configure(inspect: [charlists: :as_lists])`.

For more details, please check this Stackoverflow question: https://stackoverflow.com/questions/30037914/elixir-lists-interpreted-as-char-lists

**Comment by cigrainger** [comment] 2022-01-10 00:44
Well that's a big relief @philss, thank you. I was very confused over here. Closing, as I've confirmed it:

```elixir
iex(1)> IEx.configure(inspect: [charlists: :as_lists])
:ok
iex(2)> df = Explorer.Datasets.fossil_fuels()
#Explorer.DataFrame<
  [rows: 1094, columns: 10]
  year integer [2010, 2010, 2010, 2010, 2010, "..."]
  country string ["AFGHANISTAN", "ALBANIA", "ALGERIA", "ANDORRA", "ANGOLA",
   "..."]
  total integer [2308, 1254, 32500, 141, 7924, "..."]
  solid_fuel integer [627, 117, 332, 0, 0, "..."]
  liquid_fuel integer [1601, 953, 12381, 141, 3649, "..."]
  gas_fuel integer [74, 7, 14565, 0, 374, "..."]
  cement integer [5, 177, 2598, 0, 204, "..."]
  gas_flaring integer [0, 0, 2623, 0, 3697, "..."]
  per_capita float [0.08, 0.43, 0.9, 1.68, 0.37, "..."]
  bunker_fuels integer [9, 7, 663, 0, 321, "..."]
>
iex(3)> df |> Explorer.DataFrame.slice(0, 1) |> Explorer.DataFrame.to_map() 
%{
  bunker_fuels: [9],
  cement: [5],
  country: ["AFGHANISTAN"],
  gas_flaring: [0],
  gas_fuel: [74],
  liquid_fuel: [1601],
  per_capita: [0.08],
  solid_fuel: [627],
  total: [2308],
  year: [2010]
}
```

**Closed by cigrainger** 2022-01-10 00:44 UTC
Labels: kind:bug

**Comment by kimjoaoun** [comment] 2022-01-10 00:52
Thank you @philss and @cigrainger. Sorry for opening the useless issue. D:

**Comment by philss** [comment] 2022-01-10 01:20
@kimjoaoun no problem :)
