### ISSUE TITLE
cast integer dtype from summarise by count to i64

### ISSUE THREAD

**Issue by kylewhite21** [elixir-nx/explorer#461] opened 2023-01-04 03:10 UTC
Hi,

When I `summarise` with `count` the returning datatype is `:integer` but still seems to be tied to `u32` from polars. This is preventing me from stacking two dataframes together, one which has freshly-created ints (`i64`) and another summarized by a count (`u32`).

I can work around this by casting to float and back.

MWE below.

PS is there a way to inspect what the backend dtype is to see `i64` vs `u32`?

```
alias(Explorer.DataFrame, [as: DF])
require Explorer.DataFrame

df1 = DF.new(gp: ["a", "a", "b", "b"], val: [1, 2, 3, 4])

# summarize with no count
df2 = df1 |> DF.group_by("gp") |> DF.summarise(val: min(val))
# works
DF.concat_rows([df1, df2])

# summarize with count
df3 = df1 |> DF.group_by("gp") |> DF.summarise(val: count(val))
# fails with
# ** (RuntimeError) Data types don't match: cannot vstack: because column datatypes (dtypes) in the two DataFrames do not match for left.name='val' with left.dtype=i64 != right.dtype=u32 with right.name='val'
#     (explorer 0.4.0) lib/explorer/polars_backend/shared.ex:69: Explorer.PolarsBackend.Shared.apply_dataframe/4
DF.concat_rows([df1, df3])

# summarize with count but cast int to float and back
df4 = df3\
  |> DF.mutate(%{"val" => cast(val, :float)})\
  |> DF.mutate(%{"val" => cast(val, :integer)})
# works
DF.concat_rows([df1, df4])
```

**Comment by josevalim** [comment] 2023-01-04 10:16
Dupe of #431. :)

**Closed** 2023-01-04 10:22 UTC
